# -- nameOverride overrides the chart name
nameOverride: ""
# -- fullnameOverride overrides the full name of the chart
fullnameOverride: ""

# QLever configuration
config:
  data:
    name: default
    # name: olympics
    # base_url: https://github.com/wallscope/olympics-rdf
    # get_data_cmd: curl -sLo olympics.zip -C - https://github.com/wallscope/olympics-rdf/raw/master/data/olympics-nt-nodup.zip && unzip -q -o olympics.zip && rm olympics.zip
    # description: 120 Years of Olympics, data from https://github.com/wallscope/olympics-rdf
    # text_description: All literals, search with FILTER CONTAINS(?var, "...")
  index:
    settings_json:
      ascii-prefixes-only: false
      num-triples-per-batch: 100000

    # input_files: olympics.nt
    # cat_input_files: cat olympics.nt
  server:
    host_name: 127.0.0.1 # Hostname used to access the server ; the value of the hostname from `server.ingress.hosts[0].host` should be the same
    endpoint: http://127.0.0.1:7001 # Endpoint used to access the server from the UI
    port: 7001
    access_token: default_random_access_token
    # access_token: olympics_7643543846_Zs6nw7yi3Z9m
    memory_for_queries: 5G
    cache_max_size: 2G
    timeout: 30s
  runtime:
    system: native
  ui:
    ui_port: 7002
    ui_config: default
    # ui_config: olympics

# Service account configuration
serviceAccount:
  # -- create tells if a service account should be created
  create: false
  # -- automount tells if the service account should be automounted
  automount: true
  # -- annotations to add to the service account
  annotations: {}
  # -- name is the name of the service account to use
  name: ""

# Server configuration
server:
  # -- replicaCount is the number of replicas to deploy
  replicaCount: 1

  # Information about the Fuseki Docker image to use.
  # In case you want to use a custom image, you can set the repository and tag here.
  image:
    # -- repository is the Docker image to use
    repository: ghcr.io/zazukoians/qlever-server
    # -- pullPolicy is the policy to use when pulling the image
    pullPolicy: IfNotPresent
    # -- tag is used to overrides the image tag whose default is the chart appVersion
    tag: ""

  # -- imagePullSecrets used to pull the Docker image
  imagePullSecrets: []

  # -- podAnnotations to use
  podAnnotations: {}
  # -- podLabels to use
  podLabels: {}

  # Pod security context configuration
  podSecurityContext:
    # -- fsGroup is the group ID to run the container as
    fsGroup: 0
    # -- runAsGroup is the group ID to run the container as
    runAsGroup: 0
    # -- runAsNonRoot tells if the container should run as a non-root user
    runAsNonRoot: true
    # -- runAsUser is the user ID to run the container as
    runAsUser: 65534

  # Security context configuration
  securityContext:
    # -- allowPrivilegeEscalation tells if the container can request to allow privilege escalation
    allowPrivilegeEscalation: false
    # -- capabilities to add/drop
    capabilities: {}
    # -- privileged tells if the container is privileged
    privileged: false
    # -- runAsNonRoot tells if the container should run as a non-root user
    runAsNonRoot: true
    # -- runAsUser is the user ID to run the container as
    runAsUser: 65534
    # -- readOnlyRootFilesystem tells if the container should have a read-only root filesystem
    readOnlyRootFilesystem: false
    # -- seLinuxOptions to add
    seLinuxOptions: {}

  # Service configuration
  service:
    # -- type is the type of service to create
    type: ClusterIP
    # -- port is the port the service will listen on
    port: 7001

  # Ingress configuration
  ingress:
    # -- enabled allows you to enable or disable the Ingress
    enabled: false
    # -- className is the ingress class to use
    className: ""
    # -- annotations to add to the Ingress
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- hosts is the list of hostnames to be exposed
    hosts:
      []
      # - host: qlever-server-example.local
      #   paths:
      #     - path: /
      #       pathType: ImplementationSpecific
    # -- tls is the list of TLS configuration
    tls: []
    #  - secretName: qlever-server-example-tls
    #    hosts:
    #      - qlever-server-example.local

  # -- resources to request for the pod
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- livenessProbe is a health check to determine if the container is still running
  livenessProbe:
    tcpSocket:
      port: http

  # -- readinessProbe is a health check to determine if the container is ready to serve traffic
  readinessProbe:
    tcpSocket:
      port: http

  # -- volumes to mount on the output Deployment definition
  volumes:
    []
    # - name: data
    #   emptyDir:
    #     sizeLimit: 500Mi

  # -- volume mounts to use
  volumeMounts:
    []
    # - name: data
    #   mountPath: "/data"

  # -- nodeSelector to use
  nodeSelector: {}

  # -- tolerations to use
  tolerations: []

  # -- affinity to use
  affinity: {}

  # -- extraEnv is a list of extra environment variables to set
  extraEnv:
    []
    # - name: MY_ENV_VAR
    #   value: my-value

# UI configuration
ui:
  # -- replicaCount is the number of replicas to deploy
  replicaCount: 1

  # Information about the Fuseki Docker image to use.
  # In case you want to use a custom image, you can set the repository and tag here.
  image:
    # -- repository is the Docker image to use
    repository: ghcr.io/zazukoians/qlever-ui
    # -- pullPolicy is the policy to use when pulling the image
    pullPolicy: IfNotPresent
    # -- tag is used to overrides the image tag whose default is the chart appVersion
    tag: ""

  # -- imagePullSecrets used to pull the Docker image
  imagePullSecrets: []

  # -- podAnnotations to use
  podAnnotations: {}
  # -- podLabels to use
  podLabels: {}

  # Pod security context configuration
  podSecurityContext:
    # -- fsGroup is the group ID to run the container as
    fsGroup: 0
    # -- runAsGroup is the group ID to run the container as
    runAsGroup: 0
    # -- runAsNonRoot tells if the container should run as a non-root user
    runAsNonRoot: true
    # -- runAsUser is the user ID to run the container as
    runAsUser: 65534

  # Security context configuration
  securityContext:
    # -- allowPrivilegeEscalation tells if the container can request to allow privilege escalation
    allowPrivilegeEscalation: false
    # -- capabilities to add/drop
    capabilities: {}
    # -- privileged tells if the container is privileged
    privileged: false
    # -- runAsNonRoot tells if the container should run as a non-root user
    runAsNonRoot: true
    # -- runAsUser is the user ID to run the container as
    runAsUser: 65534
    # -- readOnlyRootFilesystem tells if the container should have a read-only root filesystem
    readOnlyRootFilesystem: false
    # -- seLinuxOptions to add
    seLinuxOptions: {}

  # Service configuration
  service:
    # -- type is the type of service to create
    type: ClusterIP
    # -- port is the port the service will listen on
    port: 7002

  # Ingress configuration
  ingress:
    # -- enabled allows you to enable or disable the Ingress
    enabled: false
    # -- className is the ingress class to use
    className: ""
    # -- annotations to add to the Ingress
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- hosts is the list of hostnames to be exposed
    hosts:
      []
      # - host: qlever-ui-example.local
      #   paths:
      #     - path: /
      #       pathType: ImplementationSpecific
    # -- tls is the list of TLS configuration
    tls: []
    #  - secretName: qlever-ui-example-tls
    #    hosts:
    #      - qlever-ui-example.local

  # -- resources to request for the pod
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- livenessProbe is a health check to determine if the container is still running
  livenessProbe:
    httpGet:
      path: "/"
      port: http

  # -- readinessProbe is a health check to determine if the container is ready to serve traffic
  readinessProbe:
    httpGet:
      path: "/"
      port: http

  # -- volumes to mount on the output Deployment definition
  volumes:
    []
    # - name: data
    #   emptyDir:
    #     sizeLimit: 500Mi

  # -- volume mounts to use
  volumeMounts:
    []
    # - name: data
    #   mountPath: "/data"
    #   readOnly: true

  # -- nodeSelector to use
  nodeSelector: {}

  # -- tolerations to use
  tolerations: []

  # -- affinity to use
  affinity: {}

  # -- extraEnv is a list of extra environment variables to set
  extraEnv:
    []
    # - name: MAP_VIEW_BASE_URL
    #   value: http://localhost:7003
    # - name: MY_ENV_VAR
    #   value: my-value
