{{- if hasKey .Values "config" -}}
  {{- if .Values.config.adminPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuseki.fullname" . }}
type: Opaque
stringData:
  adminPassword: {{ .Values.config.adminPassword }}
  {{- end -}}
{{- end -}}
