apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuseki.fullname" . }}-headless
  labels:
    {{- include "fuseki.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fuseki.selectorLabels" . | nindent 4 }}
