{{/*
Define some common variables
*/}}
{{- $configValues := .Values.config | default dict -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fuseki.fullname" . }}
  labels:
    {{- include "fuseki.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ include "fuseki.fullname" . }}-headless
  {{- if .Values.updateStrategy }}
  updateStrategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fuseki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuseki.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fuseki.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.storage.enabled .Values.volumes }}
          volumeMounts:
            {{- if .Values.storage.enabled }}
            - name: {{ include "fuseki.fullname" . }}
              mountPath: {{ .Values.storage.mountPath | quote }}
            {{- end }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- if $configValues.javaOpts }}
            - name: JAVA_OPTS
              value: {{ $configValues.javaOpts | quote }}
            {{- end }}
            {{- if $configValues.javaOpts }}
            - name: DISABLE_OTEL
              value: {{ $configValues.disableOtel | quote }}
            {{- end }}
            {{- if $configValues.adminPassword }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fuseki.fullname" . }}
                  key: adminPassword
            {{- end }}
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if or .Values.storage.enabled .Values.volumes }}
      volumes:
        {{- if .Values.storage.enabled }}
        - name: {{ include "fuseki.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "fuseki.fullname" . }}
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
