{{/*
Define some common variables
*/}}
{{- $sparqlValues := .Values.sparql | default dict -}}
{{- $configValues := .Values.config | default dict -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trifid.fullname" . }}
  labels:
    {{- include "trifid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trifid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trifid.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trifid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if $configValues.file }}
            - name: TRIFID_CONFIG
              value: {{ $configValues.file | quote }}
            {{- end }}
            - name: SPARQL_ENDPOINT_URL
              value: {{ required "The 'sparql.endpoint' field is required!" $sparqlValues.endpoint | quote }}
            {{- if $sparqlValues.username }}
            - name: SPARQL_USER
              value: {{ $sparqlValues.username | quote }}
            {{- end }}
            {{- if $sparqlValues.password }}
            - name: SPARQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifid.fullname" . }}
                  key: sparql-password
            {{- end }}
            {{- if .Values.dataset.baseUrl }}
            - name: DATASET_BASE_URL
              value: {{ .Values.dataset.baseUrl | quote}}
            {{- end }}
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
