name: Lint Charts

on:
  push:

jobs:
  lint:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Helm dependencies
        run: |
          helm dependency build zazuko/blueprint

      - name: Lint Helm Charts
        run: |
          helm lint zazuko/*
